raspberry_pi:
  espresso_button_pin: 27
  lungo_button_pin: 22
  armed_led_pin: 17
  disarmed_led_pin: 4
  arm_button_pin: -1
  check_status_button_pin: -1
  button_press_detecting_duration_ms: 300
nespresso_machine:
  button_press_duration_ms: 300
timer:
  trigger_time: "7:00"
